version: '2'

services:
  website:
    build: .
    restart: always
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "portfolio.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/portfolio'
    ports:
      - '8000:8000'
    networks:
      - portfolio_network

  proxy:
    build: proxy
    restart: always
    ports: 
      - 80:80
    networks:
      - portfolio_network

networks:
    portfolio_network:
